return PlaceObj('ModDef', {
	'title', "Earth's Last Hope",
	'description', "This mod is still a work in progress. Please hop in discord to help test and provide feedback. :)   https://discord.gg/kTgYq9UjWx",
	'image', "Images/thumbnail.png",
	'last_changes', "https://github.com/Surviving-Mars-Mods/Earths-Last-Hope",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"src/*",
		"Info/2do.txt",
		"*.iml",
		".idea/*",
		"*.png",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "FIZZLE1",
			'title', "Fizzle Fuze's Library",
			'version_major', 1,
			'version_minor', 5,
		}),
	},
	'id', "FIZZLE4",
	'steam_id', "",
	'pops_desktop_uuid', "bd64937b-89d2-46aa-b218-600efd14f8d9",
	'pops_any_uuid', "ca95f5b6-e02d-4c7d-8d8b-2b845a3acf59",
	'author', "Fizzle Fuze",
	'version_major', 1,
	'version_minor', 1,
	'version', 69,
	'lua_revision', 1009413,
	'saved_with_revision', 1010838,
	'saved', 1645327060,
	'TagCommanderProfiles', true,
	'TagMissionSponsors', true,
	'TagBuildings', true,
	'TagOther', true,
})